---
settings:
  name: SnapCenter Software 4.6
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '4.6'
    url: "/snapcenter-46"
  - version-number: '4.9'
    url: "/snapcenter"
  - version-number: '4.8'
    url: "/snapcenter-48"
  - version-number: '4.7'
    url: "/snapcenter-47"
  - version-number: '4.5'
    url: "/snapcenter-45"
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione del software SnapCenter 4.6
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - section: concept
  - section: install
  - section: protect-scsql
  - section: protect-hana
  - section: protect-sco
  - section: protect-scw
  - section: protect-sce
  - section: protect-scc
  - section: admin
  - section: upgrade
  - section: uninstall
  - section: sc-automation
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Note di rilascio
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2880779
    - title: Scopri di più su SnapCenter
      url: "/concept/concept_snapcenter_overview.html"
    - title: Guida di riferimento rapido per proteggere i database di SQL Server
      url: "/protect-scsql/quick_start_to_install_snapcenter_plug-in_for_sql_server.html"
    - title: Aggiornare il server SnapCenter e i plug-in SnapCenter
      url: "/upgrade/upgrade_workflow.html"
  - title: Installare il server SnapCenter
    links:
    - title: Licenze richieste
      url: "/install/concept_snapcenter_licenses.html"
    - title: Configurare le porte
      url: "/install/reference_connection_and_port_requirements.html"
    - title: Installare il server SnapCenter
      url: "/install/task_install_the_snapcenter_server_using_the_install_wizard.html"
    - title: Configurare la disponibilità elevata utilizzando F5
      url: "/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html"
    - title: Disaster recovery del server SnapCenter
      url: "/sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html"
  - title: Proteggere i database Microsoft SQL Server
    links:
    - title: Installare il plug-in SnapCenter per il database Microsoft SQL Server
      url: "/protect-scsql/task_add_hosts_and_install_snapcenter_plug_ins_package_for_windows.html"
    - title: Creare policy per il backup dei database di SQL Server
      url: "/protect-scsql/task_create_backup_policies_for_sql_server_databases.html"
    - title: Eseguire il backup dei database di SQL Server
      url: "/protect-scsql/task_back_up_sql_resources.html"
    - title: Disaster recovery del plug-in SnapCenter per SQL Server
      url: "/protect-scsql/task_disaster_recovery_scsql.html"
  - title: Proteggere i database SAP HANA
    links:
    - title: Installare il plug-in SnapCenter per il database SAP HANA
      url: "/protect-hana/task_add_hosts_and_install_plug_in_packages_on_remote_hosts_sap_hana.html"
    - title: Creare policy per il backup dei database SAP HANA
      url: "/protect-hana/task_create_backup_policies_for_sap_hana_databases.html"
    - title: Eseguire il backup dei database SAP HANA
      url: "/protect-hana/task_back_up_sap_hana_databases.html"
  - title: Proteggere i database Oracle
    links:
    - title: Installare il plug-in SnapCenter per il database Oracle
      url: "/protect-sco/task_add_hosts_and_installing_the_snapcenter_plug_ins_package_for_linux_or_aix.html"
    - title: Creare policy per il backup dei database Oracle
      url: "/protect-sco/task_create_backup_policies_for_oracle_database.html"
    - title: Eseguire il backup dei database Oracle
      url: "/protect-sco/task_back_up_oracle_resources.html"
  - title: Proteggere i database su VMware
    links:
    - title: Scopri di più sul plug-in SnapCenter per VMware vSphere
      url: https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/index.html
    - title: Implementare il plug-in SnapCenter per VMware vSphere
      url: https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html
  - title: Blog e community
    links:
    - title: Blog NetApp - SnapCenter
      url: https://blog.netapp.com/tag/snapcenter/
    - title: Community NetApp - SnapCenter
      url: https://community.netapp.com/t5/forums/filteredbylabelpage/board-id/backup-and-restore-discussions/label-name/snapcenter
  - title: Più risorse
    links:
    - title: Guida di riferimento per cmdlet
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2880726
    - title: Guida di riferimento ai comandi
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2880725
    - title: Documentazione per le versioni precedenti di SnapCenter
      url: https://www.netapp.com/data-protection/backup-recovery/snapcenter-backup-management/documentation/#ProseArticleLinkList13
    - title: Knowledge base di NetApp - SnapCenter
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter
