---
permalink: concept/reference_data_security.html 
sidebar: sidebar 
keywords: security,authentication, CA certificates 
summary: SnapCenter utilizza rigide funzionalità di sicurezza e autenticazione per garantire la sicurezza dei dati. 
---
= Funzionalità di sicurezza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilizza rigide funzionalità di sicurezza e autenticazione per garantire la sicurezza dei dati.

SnapCenter include le seguenti funzioni di sicurezza:

* Tutte le comunicazioni con SnapCenter utilizzano HTTP su SSL (HTTPS).
* Tutte le credenziali in SnapCenter sono protette mediante la crittografia AES (Advanced Encryption Standard).
* SnapCenter utilizza algoritmi di sicurezza conformi allo standard FIPS (Federal Information Processing Standard).
* SnapCenter supporta l'utilizzo dei certificati CA autorizzati forniti dal cliente.
* SnapCenter 4.1.1 o versione successiva supporta la comunicazione TLS (Transport Layer Security) 1.2 con ONTAP. È inoltre possibile utilizzare la comunicazione TLS 1.2 tra client e server.
* SnapCenter viene installato all'interno del firewall aziendale per consentire l'accesso al server SnapCenter e la comunicazione tra il server SnapCenter e i plug-in.
* L'API SnapCenter e l'accesso alle operazioni utilizzano token crittografati con crittografia AES, che scadono dopo 24 ore.
* SnapCenter si integra con Windows Active Directory per l'accesso e il RBAC (role-based access control) che regolano le autorizzazioni di accesso.
* I cmdlet PowerShell di SnapCenter sono protetti da sessione.
* Dopo un periodo di inattività predefinito di 15 minuti, SnapCenter avvisa che l'utente verrà disconnesso tra 5 minuti. Dopo 20 minuti di inattività, SnapCenter si disconnette ed è necessario effettuare nuovamente l'accesso. È possibile modificare il periodo di disconnessione.
* L'accesso viene temporaneamente disattivato dopo 5 o più tentativi di accesso non corretti.




== Panoramica del certificato CA

Il programma di installazione del server SnapCenter abilita il supporto centralizzato dei certificati SSL durante l'installazione. Per migliorare la comunicazione protetta tra il server e il plug-in, SnapCenter supporta l'utilizzo dei certificati CA autorizzati forniti dal cliente.

È necessario implementare i certificati CA dopo aver installato il server SnapCenter e i relativi plug-in. Per ulteriori informazioni, vedere link:../install/reference_generate_CA_certificate_CSR_file.html["Generare il file CSR del certificato CA"^].

È anche possibile distribuire il certificato CA per il plug-in SnapCenter per VMware vSphere. Per ulteriori informazioni, vedere  https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_and_import_certificates.html["Creare e importare certificati"^] .
